name: Tagging releasing and generating changelog

on:
  workflow_call:

jobs:
  tag-release-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checking repo...
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
      - name: Setup Git...
        run: |
          git config user.email "{{ secrets.BOT_EMAIL }}"
          git config user.name "B4A - Bot"
      - name: Checking changelog...
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: 'B4A - Bot'
          git-user-email: ${{ secrets.BOT_EMAIL }}
          version-file: './package.json'
          output-file: 'CHANGELOG.md'

      - name: Releasing...
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
